#!/usr/bin/env python
# -*- coding=utf-8 -*-
#头文件
import socket
import os
import struct
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)##定义socket类型，网络通信，TCP ,socket.SOCK_STREAM，流式socket , for TCP
s.connect(('192.168.132.9', 6666))   ##要连接的IP与端口
while 1:
        filepath = raw_input('please input file path: ')#文件路径，把输入的值赋值给filepth
        if os.path.isfile(filepath):  ##如果path是一个存在的文件，返回True。否则返回False。
            # 定义定义文件信息:128s表示文件名为128bytes长，l表示一个int或log文件类型，在此为文件大小
            fileinfo_size = struct.calcsize('128sl')
            # 定义文件头信息，包含文件名和文件大小
            fhead = struct.pack('128sl', os.path.basename(filepath),
                                os.stat(filepath).st_size)
            s.send(fhead)    #发送数据给服务端,包含文件名和文件大小
	    #输入文件路径
            print 'client filepath: {0}'.format(filepath)
	    #以二进制读模式打开
            fp = open(filepath, 'rb')
            while 1:
                # 每次读取 1024 个字节（即 1 KB）的内容
                data = fp.read(1024)
                
		#无法读取时停止
                if not data:
                    break
		#将读取到的字节传送
                s.send(data)
		print '{0} file send over...'.format(filepath)
		print s.recv(1024)
	#关闭文件
        fp.close()	
s.close()
	
        


